# Generated by Django 3.2.12 on 2022-04-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
